spring:
  application:
    name: eureka-service

server:
  port: 8092

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8092/eureka